### ISSUE TITLE
[Story]:  ADO ID - 17 : UI - Study Comparison - View Differences between Two Different Studies

### ISSUE THREAD

**Issue by SushmitabSinha** [transcelerate/ddf-sdr-backlog#365]
### Description

As the SDR I need to provide a view of the differences between two different studies so that I can enable a user to easily tell how a two studies differ within the SDR.

### Acceptance Criteria

GIVEN that I'm a System Admin WHEN I access the Study Comparison screen of the SDR THEN I am able to select two different studies to compare details and differences

Story Points : 8

**Comment by SushmitabSinha** [comment]
Comments:

Illakkiya Tamizh
[commented Wednesday]

Feedback from demo -
Add text/label that clearly denotes the study search and compare in study comparison screen.

aran.bahl
[commented Jan 17]

Next Step - current design is that first you need to pass a Study ID. We would need to structure APIs to not pass a particular Study ID to address this - and the UI screen was already there. 

aran.bahl
[commented Oct 1, 2021]

Comment from Berber S. - 
I am not sure whether it is relevant for an administrator who has access to the UI / dashboard to compare different studies with each other. I think this is more relevant for the upstream or downstream systems. For the MVP I would leave this requirement out.

**Comment by tamizhillakkiya** [comment]
The story is tested and closed.
