### ISSUE TITLE
[Story]: ADO ID - 1752 : Implementation of containerization for API Build & Deployment

### ISSUE THREAD

**Issue by SushmitabSinha** [transcelerate/ddf-sdr-backlog#373]
### Description

Containerizing API application.

### Acceptance Criteria

As a SDR system , containerizing the API application has to be done so that the packaged application can be deployed on any platform. 

Story Points : 5

**Comment by Mani-Chaitanya** [comment]
The backed API was containerized and deployed in Azure App Service on a test environment, and the testing was successful.

Steps performed to build and deploy container:

- Created dockerfile to pull the mcr.microsoft.com/dotnet/aspnet:6.0 docker image from docker hub and copy the build artifacts to docker image.
- Provisioned azure container registry (ACR) for managing custom container images. 
- Created Azure Pipeline tasks to build a custom container and push it to the Azure Container Private Registry.
- Provisioned app service (web app for containers).
- Created a release pipeline task to deploy the container on the web app.

**Docker File:**

![Image](https://user-images.githubusercontent.com/99388296/180707025-bdfea1b9-73db-4654-9a60-6697f333b165.png)


**Docker Pipeline Tasks:**

![Image](https://user-images.githubusercontent.com/99388296/180707210-cbd1f37a-2e2f-496a-b088-82b7406b90f5.png)
