### ISSUE TITLE
[Story]: ADO ID - 1755 : UI - Study Comparison - Unit Test Coverage

### ISSUE THREAD

**Issue by SushmitabSinha** [transcelerate/ddf-sdr-backlog#374]
### Description

Unit testing with 80% code coverage to be done for study comparison & usage report screen in the SDR application. 

### Acceptance Criteria

As a SDR developer , I need to perform unit testing for usage report and study comparison screen so that 80% of code coverage is achieved for SDR application.

Story Points : 5

**Comment by yuvarani-nagarajan** [comment]
Code coverage on end of Sprint 13 is 83%. Attached screenshot for reference.
<img width="960" alt="codeCoverage_25July" src="https://user-images.githubusercontent.com/98375969/180722873-694e7d3d-f062-4f8e-8723-9894b0aabc0c.png">
