### ISSUE TITLE
[Story]:  ADO ID - 1760 : Create API V2 - Search Study

### ISSUE THREAD

**Issue by SushmitabSinha** [transcelerate/ddf-sdr-backlog#377]
### Description

Creation of Search API V2 as per the latest USDM changes.
### Acceptance Criteria

1. As an API developer , I need to create version 2 Search study API endpoint so that the latest USDM changes can be accommodated.
2. As a SDR system , when the search criteria is sent in the request body, the relevant data that satisfy the search criteria must be retrieved using Search API as per latest USDM changes.

Story Points : 5

**Comment by Viswesh-Mb** [comment]
Created a new endpoint the details are below.
POST Method:
URL: https://apim-sdr-qa-eastus.azure-api.net/api/v1/studydefinitions/ui/v1/search

Request, Response JSON and screenshot for the Postman request and response are attached.
Zipped Files for request and response JSON files for the POST API:
[Search_Request&ResponseJSONFiles.zip](https://github.com/transcelerate/ddf-sdr-backlog/files/9160212/Search_Request.ResponseJSONFiles.zip)

Postman Screenshot
![PostmanScreenshot](https://user-images.githubusercontent.com/98514384/180241529-93037289-538b-48dc-8a2b-138f3b8183c8.JPG)
