### ISSUE TITLE
[Story]: ADO ID - 1817 : Testing: Creation of Automation script in JMeter for POST API - V2

### ISSUE THREAD

**Issue by SushmitabSinha** [transcelerate/ddf-sdr-backlog#384]
### Description

Test Automation Script Creation in JMeter for POST API-V2.

### Acceptance Criteria

As and SDR System Tester, I need to create automation script in JMeter for POST API-V2.

Story Points : 5

**Comment by rupamazumder** [comment]
[Uploading Build-Artifact (9).zip…] (Evidence for automation script JMX report)
