### ISSUE TITLE
[Bug]: ADO ID - 1809 : API : POST Group, GET Group, GET GroupList APIs giving 400 error

### ISSUE THREAD

**Issue by SushmitabSinha** [transcelerate/ddf-sdr-backlog#406]
### Steps to reproduce the Bug.

1. Invoke the POST Group, GET Group, GET GroupList APIs 
2. Observation: All the APIs are giving 400 error

### Bug prevalence

.

**Comment by SushmitabSinha** [comment]
Comments:

r.mazumder
[commented Monday]

Issue again found in QA Environment. So REOPENING the issue. @viswesh.mb 

r.mazumder
[commented Jul 15]

Issue retested and CLOSED. Evidence attached.

viswesh.mb
[commented Jul 14]

Issue: On moving the UserGroupsController to shared folder, after deployment, there was an issue in getting data from database. 
Resolution: After moving the UserGroupsController out of the shared folder, the issue was resolved.

**Comment by SushmitabSinha** [comment]
[ISSUE FIX.webm](https://user-images.githubusercontent.com/98328753/180611160-94cae0d8-f29a-495c-bdd1-d137ea17be69.webm)

**Comment by Viswesh-Mb** [comment]
The issue has not occurred for a week. There has been 4 deployments since last time the issue occurred. Hence closing the bug.
